sudo: required
services:
  - docker

before_install:
  - docker build -t timdinia/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true timdinia/react-tests yarn test

after_success:
  - docker build -t timdinia/multi-client ./client
  - docker build -t timdinia/multi-nginx ./nginx
  - docker build -t timdinia/multi-server ./server
  - docker build -t timdinia/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push timdinia/multi-client
  - docker push timdinia/multi-nginx
  - docker push timdinia/multi-server
  - docker push timdinia/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker2
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-eu-west-3-209313652649
  bucket_path: multi-docker2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
